# Generated by Django 5.0.1 on 2024-01-22 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDinamico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=500)),
                ('data_criacao', models.DateField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questao_texto', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('escolha_unica', 'Escolha Única'), ('multipla_escolha', 'Escolha Múltipla'), ('texto', 'Texto'), ('true_false', 'Verdadeiro ou Falso'), ('data', 'Data'), ('numero', 'Número')], max_length=20)),
                ('itens', models.JSONField(blank=True, max_length=1000, null=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.formdinamico')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_texto', models.CharField(max_length=255)),
                ('data_resposta', models.DateField()),
                ('hora', models.TimeField()),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.questao')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
